all: mainScreen doneScreen playScreen guessMatchedScreen guessDidntMatchScreen currentReferenceUndefined helpScreen0 helpScreen1 helpScreen2 helpScreen3

mainScreen: ../webgraphics/mainScreen.png
	convert ../webgraphics/mainScreen.png -resize "1024x" mainScreen.jpg

doneScreen: ../webgraphics/doneScreen.png
	convert ../webgraphics/doneScreen.png -resize "1024x" doneScreen.jpg

playScreen: ../webgraphics/playScreen.png
	convert ../webgraphics/playScreen.png -resize "1024x" playScreen.jpg

guessMatchedScreen: ../webgraphics/guessMatchedScreen.png
	convert ../webgraphics/guessMatchedScreen.png -resize "1024x" guessMatchedScreen.jpg

guessDidntMatchScreen: ../webgraphics/guessDidntMatchScreen.png
	convert ../webgraphics/guessDidntMatchScreen.png -resize "1024x" guessDidntMatchScreen.jpg

currentReferenceUndefined: ../webgraphics/currentReferenceUndefined.png
	convert ../webgraphics/currentReferenceUndefined.png -resize "1024x" currentReferenceUndefined.jpg

helpScreen0: ../webgraphics/helpScreen0.png
	convert ../webgraphics/helpScreen0.png -resize "1024x" helpScreen0.jpg

helpScreen1: ../webgraphics/helpScreen1.png
	convert ../webgraphics/helpScreen1.png -resize "1024x" helpScreen1.jpg

helpScreen2: ../webgraphics/helpScreen2.png
	convert ../webgraphics/helpScreen2.png -resize "1024x" helpScreen2.jpg

helpScreen3: ../webgraphics/helpScreen3.png
	convert ../webgraphics/helpScreen3.png -resize "1024x" helpScreen3.jpg



# didntMatch1.png: ../webgraphics/sorryScreen2.png
# 	convert ../webgraphics/sorryScreen2.png -resize "1024x" didntMatch1.png

# didntMatch2.png: ../webgraphics/sorryScreen3.png
# 	convert ../webgraphics/sorryScreen3.png -resize "1024x" didntMatch2.png

# didntMatch3.png: ../webgraphics/sorryScreen4.png
# 	convert ../webgraphics/sorryScreen4.png -resize "1024x" didntMatch3.png

# levelCompleteBackground.png: ../webgraphics/screenLevelCleared.png
# 	convert ../webgraphics/screenLevelCleared.png -resize "1024x" levelCompleteBackground.png

# playScreen.png: ../webgraphics/screenGuess.png
# 	convert ../webgraphics/screenGuess.png -resize "1024x" playScreen.png

# guessMatchedScreen.png: ../webgraphics/congratulationScreen.png
# 	convert ../webgraphics/congratulationScreen.png -resize "1024x" guessMatchedScreen.png

# helpScreen0.png: ../webgraphics/helpScreen0.png
# 	convert ../webgraphics/helpScreen0.png -resize "1024x" helpScreen0.png

# helpScreen1.png: ../webgraphics/helpScreen1.png
# 	convert ../webgraphics/helpScreen1.png -resize "1024x" helpScreen1.png

# helpScreen2.png: ../webgraphics/helpScreen2.png
# 	convert ../webgraphics/helpScreen2.png -resize "1024x" helpScreen2.png

# helpScreen3.png: ../webgraphics/helpScreen3.png
# 	convert ../webgraphics/helpScreen3.png -resize "1024x" helpScreen3.png

# helpScreenBackground.png: ../webgraphics/helpScreenBackground.png
# 	convert ../webgraphics/helpScreenBackground.png -resize "1024x" helpScreenBackground.png

# pauseScreenBackground.png: ../webgraphics/levelsScreen.png
# 	convert ../webgraphics/levelsScreen.png -resize "1024x" pauseScreenBackground.png

# pickReferenceCallScreen.png: ../webgraphics/pickReferenceCallScreen.png
# 	convert ../webgraphics/pickReferenceCallScreen.png -resize "1024x" pickReferenceCallScreen.png

# scoreBoardScreen.png: ../webgraphics/levelsLockedBackground.png
# 	convert ../webgraphics/levelsLockedBackground.png -resize "1024x" scoreBoardScreen.png

# achievementsScreen.png: ../webgraphics/achievementsScreen.png
# 	convert ../webgraphics/achievementsScreen.png -resize "1024x" achievementsScreen.png
