all: forwardButton.png forwardButtonPressed.png mainPlayButton.png mainPlayButtonPressed.png nextButton.png nextButtonPressed.png selectButton.png selectButtonPressed.png tryAgainButton.png tryAgainButtonPressed.png

clean:
	rm *png

forwardButton.png: ../../webgraphics/ornithopedia/forwardButton.png
	convert ../../webgraphics/ornithopedia/forwardButton.png -resize 85x83 forwardButton.png

forwardButtonPressed.png: ../../webgraphics/ornithopedia/forwardButtonPressed.png
	convert ../../webgraphics/ornithopedia/forwardButtonPressed.png -resize 85x83 forwardButtonPressed.png

mainPlayButton.png: ../../webgraphics/ornithopedia/mainPlayButton.png
	convert ../../webgraphics/ornithopedia/mainPlayButton.png -resize 400x mainPlayButton.png

mainPlayButtonPressed.png: ../../webgraphics/ornithopedia/mainPlayButtonPressed.png
	convert ../../webgraphics/ornithopedia/mainPlayButtonPressed.png -resize 400x mainPlayButtonPressed.png

nextButton.png: ../../webgraphics/ornithopedia/nextButton.png
	convert ../../webgraphics/ornithopedia/nextButton.png -resize 200x nextButton.png

nextButtonPressed.png: ../../webgraphics/ornithopedia/nextButtonPressed.png
	convert ../../webgraphics/ornithopedia/nextButtonPressed.png -resize 200x nextButtonPressed.png

selectButton.png: ../../webgraphics/ornithopedia/selectButton.png
	convert ../../webgraphics/ornithopedia/selectButton.png -resize 200x selectButton.png

selectButtonPressed.png: ../../webgraphics/ornithopedia/selectButtonPressed.png
	convert ../../webgraphics/ornithopedia/selectButtonPressed.png -resize 200x selectButtonPressed.png

tryAgainButton.png: ../../webgraphics/ornithopedia/tryAgainButton.png
	convert ../../webgraphics/ornithopedia/tryAgainButton.png -resize 300x tryAgainButton.png

tryAgainButtonPressed.png: ../../webgraphics/ornithopedia/tryAgainButtonPressed.png
	convert ../../webgraphics/ornithopedia/tryAgainButtonPressed.png -resize 300x tryAgainButtonPressed.png

